### ISSUE TITLE
Extra ledMatrix[2][1] = 1;

### ISSUE THREAD

**Issue by jonathanrjpereira** [DIY-Machines/Word-Clock#2]
Lines **143** & **159**: I think you may have added an extra `ledMatrix[2][1] = 1;`

143:    `ledMatrix[2][1] = 1; //Should this be [2][2] ?`
144:    `Serial.print("mtwenty five ");`

159:    `ledMatrix[2][1] = 1;`
160:    `Serial.print("mtwenty five ");`

**Comment by jonathanrjpereira** [comment]
Similar issue pointed out by user **Jollet71717** on Electromaker.io

> I noticed that on line 103 - 104 you have 
> 
>     //write 'it is' everytime:
>     ledMatrix[0][0] = 1;
>     ledMatrix[0][1] = 1;
>     ledMatrix[0][0] = 1;
> 
> It looks like you possibly duplicated 'ledMatrix[0][0] = 1;

**Comment by DIY-Machines** [comment]
Hello, yes you're right in both cases. I have updated the code to correct this. Thank you for pointing it out. :)
